/*
 * ForceFileReader.h
 *
 *  Created on: 27/06/2017
 *      Author: blackzafiro
 *
 * Reads the files generated by the National Instruments application I
 * modified.
 * Used for the second round of experiments.
 */

#ifndef INCLUDE_PERCEPTION_FORCEFILEREADER_H_
#define INCLUDE_PERCEPTION_FORCEFILEREADER_H_

#include <iostream>
#include <iomanip>
#include <fstream>
#include <string>

namespace Perception {

class SensedForce
{
	public:
	double fx, fy, fz;
	double tx, ty, tz;
	double d;           // d = tx*tx + ty*ty;
	SensedForce ();
};

std::ostream& operator << (std::ostream &o, const SensedForce& f);

class SensorFileReader
{
private:
	std::ifstream sensorFile;
	std::string line;

	// read elements
	float time;
	SensedForce force;
	float prevTime;
	SensedForce prevForce;

	int readLine(SensedForce &sf, float &time);

public:
		SensorFileReader();

		/**
		 * Opens file with force information.
		 * @returns -1 if there was an error opening the file,
		 *          0 is everything is fine.
		 */
		int init (const char* s);

		/**
		 * 6 element vector <Fx,Fy,Fz,Tx,Ty,Tz>
		 * @returns -1 if it finished reading or the file is not open.
		 */
		int readLine();

		float getTimestamp();
		SensedForce& getForce();
		float getPrevTimestamp();
		SensedForce& getPrevForce();
		void close();
};

}



#endif /* INCLUDE_PERCEPTION_FORCEFILEREADER_H_ */
